# Generated by Django 3.2.20 on 2023-07-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
