# Generated by Django 3.2.20 on 2023-07-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler_app', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
