# Generated by Django 3.2.20 on 2023-07-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler_app', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
